### ISSUE TITLE
Time series sampling of kmeans is unstable

### ISSUE THREAD

**Issue by rbavery** [agroimpacts/cloud-free-planet#8]
some planet images have extremely high HOT indices that bias the kmeans clustering to have a very high cluster center that is only applicable to a few images. Currently exploring how a upper HOT threshold to winnow down the sample affects the single kmeans model. 

Having a single set of cluster centers from this single model will simplify and expedite processing time, and allow for closer comparison with the IDL version, which uses a single set of cluster centers to compute the NRDI and upper threshold, U.

**Comment by rbavery** [comment]
NRDI (adjust_T in the IDL code) is a problem here because the HOT indices 
vary a lot in the planet images. if we train a kmeans model for each image
Th_initial will have a very low initial value, if we train one kmeans model from a sample
then the model will produce inaccurate initial masks because of extremely high
HOT values that skew the three clusters such that many images in the time series have thick, thin, and land misclassified. Need to find a work around, possibly using 4 clusters to account for super high HOT values or prefilitering HOT values to be within a reasonable range for land, thin, and thick clouds (currently implemented in sample_and_kmeans)

Below are some examples from the single kmeans model, where the clusters are not mapped correctly compared to kmeans per image
![Selection_578](https://user-images.githubusercontent.com/22258697/54900041-13251d00-4e8f-11e9-81ad-09de18eda8c7.png)
![Selection_577](https://user-images.githubusercontent.com/22258697/54900042-13251d00-4e8f-11e9-9bf1-e17a08526300.png)

**Comment by ldemaz** [comment]
Other possible approaches per our discussion seem to be:

- [ ] setting a more aggressive HOT line I.e. the 1.5 recommended by lit?
- [ ] normalize time series before calculating upper threshold

That's what I take away from our call...

**Comment by rbavery** [comment]
It's clear that this is a problem with the python code and not the planet data or original algorithm. A single kmeans model sampled from the time series is the best way to go, as per the original. To Do

Check the hot images generated by IDL ATSA and compare with HOT values generated by pyATSA
compare kmeans outputs (need to figure out how to save these out using IDL by looking at other parts of the code where images are saved)
Figure out where the difference is. Also would be quick to compare the kmeans centers between the two versions

**Comment by rbavery** [comment]
This is fixed, the final cloud masks now look nearly identical to the idl versions. The only differences are minor and happen because of the method for initializing kmeans (Zhu used the mean and standard deviation of the sample rather than a more conventional random initialization) and because I haven't put in morphological opening yet
